### ISSUE TITLE
Crash when pinning item

### ISSUE THREAD

**Issue by MaxVonMustermann** [Dominic-DallOsto/zotero-pin-items#1]
Hey there! Thank you for all the great plugins that are very much improving the Zotero user interface! This plugin is another small little addition!
Sadly, it doesn't work for me. Installing works fine, enabling the column itself. Marking a file with a pin via the right-click context menu causes Zotero to crash. I hope this can be fixed!

Edit: I just figured out that this crash only occurs when tryping to pin note files. Parent files work fine.

**Comment by Dominic-DallOsto** [comment]
Ahh, thanks for the detailed info - that makes it easy to fix!

**Comment by MaxVonMustermann** [comment]
> 🚀 _This ticket has been resolved in v0.1.1. See [Release 0.1.1](https://github.com/Dominic-DallOsto/zotero-pin-items/releases/tag/v0.1.1) for release notes._

It seems that is does not have been resolved. This is due to the pin item option in the context menu has completely disappeared from any file that is not a parent file.

**Comment by Dominic-DallOsto** [comment]
Ahh yeah - sorting only works on parent items, so it's only possible to pin them. It was just a bug that this option was being shown for attachments/notes, and Zotero would crash when you tried to pin them.
