### ISSUE TITLE
Sorting order of non-pinned items

### ISSUE THREAD

**Issue by MaxVonMustermann** [Dominic-DallOsto/zotero-pin-items#2]
Hey there.
I am wondering: What is the logic of the sorting order for non-pinned items? Maybe this can be modified, so non-pinned items are sorted alphabetically, if pin-sorting is enabled?

**Comment by MaxVonMustermann** [comment]
This already works, I didn't know secondary sorting was already a thing! Sorry.

**Comment by MaxVonMustermann** [comment]
I just noticed that that sorting by name inverts the sorting logic. If you want pinned items on top, the non-pinned ones are sorted in an inverted order. In order to sort them alphabetically, pinned items have to stay on the bottom.
Maybe this is a Zotero limitation, but maybe it can be fixed somehow.

**Comment by Dominic-DallOsto** [comment]
Hmm yeah, I can't immediately find a way to change the secondary sorting order independently from the primary sorting order.

If it isn't possible, worst case I can add a custom setting to swap the sorting of pinned items, so you can swap the secondary sorting order and keep the pinned items on top.

**Comment by Dominic-DallOsto** [comment]
I just added some options for changing the sort order in the latest version - let me know if this fixes your problem!
